version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  ruby-linter: amyroi/ruby-linter@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/ruby:2.6.3'
    steps:
      - checkout
      - ruby-linter/brakeman:
          parallel: true