
name: brakeman-scanner
on: [pull_request]

jobs:
  brakeman-scanner:
    name: runner / brakeman
    runs-on: ubuntu-latest
  
    steps:
      - run: |
          gem install brakeman && brakeman . || true
