name: Nuclei Scan

on: push

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://example.com
        
      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
        
      - uses: indentinc/github-action-slack-notify@master
        with:
          status: ${{ job.status }}
          author_name: Vulnerability Assessment - Nuclei Scan
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
