name: Nuclei - DAST Scan

on: push

jobs:
  worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - uses: projectdiscovery/nuclei-action@main

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/go/bin/nuclei
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/go/bin/nuclei') }}

      - uses: projectdiscovery/nuclei-action@main
        with:
          name: projectdiscovery/nuclei-templates@master
          target: "http://e53d-59-103-104-32.ngrok.io"
          templates: "nuclei-templates"
          output: "nuclei.log"

      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
