name: Nuclei Scan

on:
    schedule:
      - cron: '* * * * *'
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Nuclei - DAST Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: "github-actions/urls.txt"
        
      - uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
        
      - uses: indentinc/github-action-slack-notify@master
        with:
          status: ${{ job.status }}
          author_name: Vulnerability Assessment - Nuclei Scan
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
