name: Nuclei Scan

on: push

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url:
        - http://e53d-59-103-104-32.ngrok.io
    steps:
    - name: Scan ${{ matrix.url }} with Nuclei
      uses: projectdiscovery/nuclei-action@508c1868d4884e9fb6eb4d8d680cbc6b493c7ec5
      with:
        target: ${{ matrix.url }}
        output: "nuclei.log"
        
    - uses: actions/upload-artifact@v2
      with:
        name: nuclei.log
        path: nuclei.log
        
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: "{\"key\":\"value\",\"foo\":\"bar\"}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
