name: brakeman-scanner
on: push

jobs:
  brakeman-scanner:
    name: runner / brakeman
    runs-on: ubuntu-latest
  
    steps:
      - run: |
          sodo gem install brakeman && brakeman . || true
